#!/usr/bin/expect -f
set LOCATION [lindex $argv 0]
if { [string compare $LOCATION ""] == 0 } {
    set LOCATION "vpn-1-gci.corp.tw1.yahoo.com/GeneralHybrid"
}
spawn vpn con $LOCATION
expect "Username:"
send "ehuang02\r"
expect "Password:"
send "$env(OKTA)\r"
expect "Second Password:"
send "push\r"
interact
